version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - ../postgre/db:/var/lib/postgresql/data
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
